In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix,accuracy_score

In [2]:
data = pd.read_csv('heart.csv')

In [3]:
data.count()

age         303
sex         303
cp          303
trtbps      303
chol        303
fbs         303
restecg     303
thalachh    303
exng        303
oldpeak     303
slp         303
caa         303
thall       303
output      303
dtype: int64

In [4]:
age = data.iloc[:,0:1].values
Sex = data.iloc[:,1:2].values
values = data.iloc[:,2:13].values
Output = data.iloc[:,13].values

In [5]:
print(Sex[2])
print(values[1])

[0]
[  2.  130.  250.    0.    1.  187.    0.    3.5   0.    0.    2. ]


In [6]:
data.head()

age  sex  cp  trtbps  chol  fbs  restecg  thalachh  exng  oldpeak  slp  \
0   63    1   3     145   233    1        0       150     0      2.3    0   
1   37    1   2     130   250    0        1       187     0      3.5    0   
2   41    0   1     130   204    0        0       172     0      1.4    2   
3   56    1   1     120   236    0        1       178     0      0.8    2   
4   57    0   0     120   354    0        1       163     1      0.6    2   

   caa  thall  output  
0    0      1       1  
1    0      2       1  
2    0      2       1  
3    0      2       1  
4    0      2       1

# categorized

In [7]:
ohe = preprocessing.OneHotEncoder()
sex = ohe.fit_transform(data.iloc[:,1:2]).toarray()
print(sex)

[[0. 1.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 

In [8]:
le = preprocessing.LabelEncoder()
sick = le.fit_transform(data.iloc[:,13:])
print(sick)

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0]


C:\Users\asus\AppData\Roaming\Python\Python39\site-packages\sklearn\preprocessing\_label.py:115: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [9]:
gender = pd.DataFrame(data=sex,index=range(303),columns=['M','F'])

## Veri Birleştirme

In [10]:
Age = pd.DataFrame(data=age,index=range(303),columns=['Age'])
Middlearea = pd.DataFrame(data=values,index=range(303),columns=['cp','trtbps','chol','fbs','restecg','thalachh','exng','oldpeak','slp','caa','thall'])
result = pd.DataFrame(data=sick,index=range(303),columns=['heart disease'])

In [11]:
t = pd.concat([Age,gender],axis=1)
print(t)

     Age    M    F
0     63  0.0  1.0
1     37  0.0  1.0
2     41  1.0  0.0
3     56  0.0  1.0
4     57  1.0  0.0
..   ...  ...  ...
298   57  1.0  0.0
299   45  0.0  1.0
300   68  0.0  1.0
301   57  0.0  1.0
302   57  1.0  0.0

[303 rows x 3 columns]


In [12]:
t2 = pd.concat([t,Middlearea],axis=1)
print(t2)

     Age    M    F   cp  trtbps   chol  fbs  restecg  thalachh  exng  oldpeak  \
0     63  0.0  1.0  3.0   145.0  233.0  1.0      0.0     150.0   0.0      2.3   
1     37  0.0  1.0  2.0   130.0  250.0  0.0      1.0     187.0   0.0      3.5   
2     41  1.0  0.0  1.0   130.0  204.0  0.0      0.0     172.0   0.0      1.4   
3     56  0.0  1.0  1.0   120.0  236.0  0.0      1.0     178.0   0.0      0.8   
4     57  1.0  0.0  0.0   120.0  354.0  0.0      1.0     163.0   1.0      0.6   
..   ...  ...  ...  ...     ...    ...  ...      ...       ...   ...      ...   
298   57  1.0  0.0  0.0   140.0  241.0  0.0      1.0     123.0   1.0      0.2   
299   45  0.0  1.0  3.0   110.0  264.0  0.0      1.0     132.0   0.0      1.2   
300   68  0.0  1.0  0.0   144.0  193.0  1.0      1.0     141.0   0.0      3.4   
301   57  0.0  1.0  0.0   130.0  131.0  0.0      1.0     115.0   1.0      1.2   
302   57  1.0  0.0  1.0   130.0  236.0  0.0      0.0     174.0   0.0      0.0   

     slp  caa  thall  
0   

In [13]:
x_train,x_test,y_train,y_test = train_test_split(t2,result,test_size=0.20,random_state=0)

In [14]:
y_train

heart disease
74               1
153              1
64               1
296              0
287              0
..             ...
251              0
192              0
117              1
47               1
172              0

[242 rows x 1 columns]

In [15]:
sc = StandardScaler()
X_train = sc.fit_transform(x_train)


## Logistic Regression

In [16]:
loreg = LogisticRegression(random_state=0)
loreg.fit(X_train,y_train)
y_pred = loreg.predict(x_test)
cm = confusion_matrix(y_test,y_pred)
ac = accuracy_score(y_test,y_pred)
print(cm)
print(ac)

[[27  0]
 [28  6]]
0.5409836065573771


C:\Users\asus\AppData\Roaming\Python\Python39\site-packages\sklearn\utils\validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\asus\AppData\Roaming\Python\Python39\site-packages\sklearn\base.py:443: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  warnings.warn(


## SVC

In [17]:
svm = SVC(kernel='poly')
svm.fit(X_train,y_train)
y_pred = svm.predict(x_test)
cm2 = confusion_matrix(y_test,y_pred)
ac2 = accuracy_score(y_test,y_pred)
print(cm2)
print(ac2)

[[ 2 25]
 [ 3 31]]
0.5409836065573771


C:\Users\asus\AppData\Roaming\Python\Python39\site-packages\sklearn\utils\validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\asus\AppData\Roaming\Python\Python39\site-packages\sklearn\base.py:443: UserWarning: X has feature names, but SVC was fitted without feature names
  warnings.warn(


## KNN

In [18]:
knn = KNeighborsClassifier(n_neighbors=15,metric='euclidean')
knn.fit(X_train,y_train)
y_pred = knn.predict(x_test)
cm3 = confusion_matrix(y_test,y_pred)
ac3 = accuracy_score(y_test,y_pred)
print(cm3)
print(ac3)

[[ 0 27]
 [ 0 34]]
0.5573770491803278


C:\Users\asus\AppData\Roaming\Python\Python39\site-packages\sklearn\neighbors\_classification.py:200: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
C:\Users\asus\AppData\Roaming\Python\Python39\site-packages\sklearn\base.py:443: UserWarning: X has feature names, but KNeighborsClassifier was fitted without feature names
  warnings.warn(


## Gaus

In [19]:
na = GaussianNB()
na.fit(X_train,y_train)
y_pred = na.predict(x_test)
cm4 = confusion_matrix(y_test,y_pred)
ac4 = accuracy_score(y_test,y_pred)
print(cm4)
print(ac4)

[[ 3 24]
 [10 24]]
0.4426229508196721


C:\Users\asus\AppData\Roaming\Python\Python39\site-packages\sklearn\utils\validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\asus\AppData\Roaming\Python\Python39\site-packages\sklearn\base.py:443: UserWarning: X has feature names, but GaussianNB was fitted without feature names
  warnings.warn(


## Decision Tree

In [20]:
dt = DecisionTreeClassifier()
dt.fit(X_train,y_train)
y_pred = dt.predict(x_test)
cm5 = confusion_matrix(y_test,y_pred)
ac5 = accuracy_score(y_test,y_pred)
print(cm5)
print(ac5)

[[26  1]
 [26  8]]
0.5573770491803278


C:\Users\asus\AppData\Roaming\Python\Python39\site-packages\sklearn\base.py:443: UserWarning: X has feature names, but DecisionTreeClassifier was fitted without feature names
  warnings.warn(


## Random Forest

In [21]:
rf = RandomForestClassifier(random_state=0)
rf.fit(X_train,y_train)
y_pred = rf.predict(x_test)
cm6 = confusion_matrix(y_test,y_pred)
ac6 = accuracy_score(y_test,y_pred)
print(cm6)
print(ac6)

[[25  2]
 [25  9]]
0.5573770491803278


C:\Users\asus\AppData\Local\Temp/ipykernel_3128/3425029499.py:2: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  rf.fit(X_train,y_train)
C:\Users\asus\AppData\Roaming\Python\Python39\site-packages\sklearn\base.py:443: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
